/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    PlayStopButton: typeof import('./src/components/PlayStopButton.vue')['default']
    SourceSelector: typeof import('./src/components/SourceSelector.vue')['default']
    StatusIndicator: typeof import('./src/components/StatusIndicator.vue')['default']
    Tile: typeof import('./src/components/Tile.vue')['default']
  }
}
